# Trino worker — lakehouse-lab
coordinator=false
http-server.http.port=8080
discovery.uri=http://trino-coordinator:8080

query.max-memory=${ENV:TRINO_QUERY_MAX_MEMORY}
query.max-memory-per-node=${ENV:TRINO_QUERY_MAX_MEMORY_PER_NODE}
